/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lox;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    void appHasAGreeting() {
        Lox classUnderTest = new Lox();
    }
}
